### ISSUE TITLE
Support -files flag for sds++

### ISSUE THREAD

**Issue by boitumeloruf** [tulipp-eu/sthem#7]
When distributing code of a hardware function amongst multiple source files, in order to preserve clarity of the project source, the sds++ needs to knwo about these files by adding them with -files flag. In the project.sdx file these files are mentioned in <hls_files> tag.

https://www.xilinx.com/html_docs/xilinx2018_2/sdsoc_doc/hardware-function-options-icf1504034400618.html

**Comment by djupdal** [comment]
Can't find the hls_files tag in 2018.2.  Would it be acceptable to give all source files (related and unrelated) to the -files flag?

**Comment by boitumeloruf** [comment]
It might work, but I have not tried it before. Otherwise, here is an example project.sdx file from our use case : https://github.com/tulipp-eu/tulipp-use-cases/blob/master/uav/Tulipp_SgmStereo_Ultrascale_CL/project.sdx

**Comment by djupdal** [comment]
Fixed more properly by analysing the sources, now only adds the correct files to the -files flag.

**Comment by boitumeloruf** [comment]
Issue not fixed yet. FileList behind -files flag needs to be comma seperated. See: "Specify a comma-separated list (without white space) of one or more files required to compile the current top-level function into hardware using Vivado HLS" in https://github.com/tulipp-eu/tulipp-use-cases/blob/master/uav/Tulipp_SgmStereo_Ultrascale_CL/project.sdx

**Comment by djupdal** [comment]
Try now, please report if it works or not.

**Comment by boitumeloruf** [comment]
It is busy running. So far no error. I will let you know if it succeeds.

**Comment by boitumeloruf** [comment]
Now I get an error for projects with only one file per hw function. In this case the -files flag is added to sds++ but no files are added after the flag.

`
sds++ -I/home/rufboi/sdx_workspace/Tulipp_SgmStereo_Ultrascale/src -I/home/rufboi/sdx_workspace/Tulipp_SgmStereo_Ultrascale/src/"../src" -I/home/rufboi/sdx_workspace/Tulipp_SgmStereo_Ultrascale/src/C:/Tulipp_SgmStereo_Ultrascale/platforms/emc2_hdmi_ultra/sw/standalone/inc/include -DHALF_ENABLE_CPP11_CMATH=0   -sds-sys-config standalone -sds-proc a53_0  -sds-pf /home/rufboi/sdx_workspace/Tulipp_SgmStereo_Ultrascale/pfm/emc2_hdmi_ultra -target-os standalone -dmclkid 0 -sds-hw sgm_rgba /home/rufboi/sdx_workspace/Tulipp_SgmStereo_Ultrascale/src/sgm.cpp -files  -clkid 0 -sds-end -c /home/rufboi/sdx_workspace/Tulipp_SgmStereo_Ultrascale/src/sgm.cpp -o sgm.o
`

**Comment by djupdal** [comment]
You are right, I managed to break the common case.  Now it should work again, please report.

**Comment by boitumeloruf** [comment]
Above issues seem to be fixed. However, I get a new error now: https://github.com/tulipp-eu/sthem/issues/11
